sonar.organization=jesusruizchico
sonar.projectKey=JesusRuizChico_front-check
sonar.projectName=front-check
 
sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
 
# Cobertura generada por "flutter test --coverage"
sonar.dart.lcov.reportPaths=coverage/lcov.info
 
